### ISSUE TITLE
Makefile contains wrong version reference for 2.8

### ISSUE THREAD

**Issue by jeanparker** [awslabs/aws-viewer-for-cbmc#66]
Installation of version 2.8 fails with 

> ERROR: Could not install packages due to an EnvironmentError: [Errno 2]  file cbmc_viewer-2.0-py3-none-any.whl not found  

See:
https://github.com/awslabs/aws-viewer-for-cbmc/blob/2085aac8d1c31528ae042ed375c320b0d8d14463/Makefile#L65

**Comment by ActoryOu** [comment]
I met this same issue, and I can install successfully by changing it to "dist/cbmc_viewer-**2.8**-py3-none-any.whl"

**Comment by markrtuttle** [comment]
I will fix this.  

General users should be installing the pip package on the release page: https://github.com/awslabs/aws-viewer-for-cbmc/releases/tag/viewer-2.8
